ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'ANALISIS';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'DISENO';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'DESARROLLO_IMPLEMENTACION';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'PRUEBAS';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'TRANSICION';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'PUESTA_EN_MARCHA';

ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'ANALISIS';
ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'DISENO';
ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'DESARROLLO_IMPLEMENTACION';
ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'PRUEBAS';
ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'TRANSICION';
ALTER TYPE "StoryStatus" ADD VALUE IF NOT EXISTS 'PUESTA_EN_MARCHA';

ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'ANALISIS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'DISENO';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'DESARROLLO_IMPLEMENTACION';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'PRUEBAS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'TRANSICION';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'PUESTA_EN_MARCHA';
