-- Add board phase values to task status enum so requerimientos can use the same states.
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'ANALISIS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'DISENO';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'DESARROLLO_IMPLEMENTACION';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'PRUEBAS';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'TRANSICION';
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'PUESTA_EN_MARCHA';
